/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kantinku;

import java.awt.Color;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Kris Cyber
 */
public class Login extends javax.swing.JFrame {

    int dragxmouse;
    int dragymouse;
        
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    public static String nama,id;
    
    public Login() {
        initComponents();
        this.setBackground(new Color(0,0,0,0));
        Koneksi DB = new Koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JButton();
        sbg = new javax.swing.JComboBox<>();
        pasword = new javax.swing.JPasswordField();
        uname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        eksit = new javax.swing.JButton();
        layot = new javax.swing.JLabel();
        geser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(375, 165));
        setMinimumSize(new java.awt.Dimension(620, 440));
        setUndecorated(true);
        getContentPane().setLayout(null);

        login.setBackground(new java.awt.Color(0, 102, 255));
        login.setFont(new java.awt.Font("BlackHole BB", 1, 36)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("LOGIN");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login);
        login.setBounds(160, 343, 300, 40);

        sbg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "         ", "Pembeli", "Penjual", "Kasir" }));
        getContentPane().add(sbg);
        sbg.setBounds(306, 270, 150, 20);
        getContentPane().add(pasword);
        pasword.setBounds(160, 220, 300, 30);

        uname.setFont(new java.awt.Font("Antigrav BB", 2, 24)); // NOI18N
        getContentPane().add(uname);
        uname.setBounds(160, 130, 300, 30);

        jLabel4.setFont(new java.awt.Font("Antigrav BB", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Login sebagai:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(160, 260, 150, 40);

        jLabel3.setFont(new java.awt.Font("Antigrav BB", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 174, 620, 30);

        jLabel1.setFont(new java.awt.Font("BlackHole BB", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Selamat Datang");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 10, 620, 60);

        jLabel2.setFont(new java.awt.Font("Antigrav BB", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Username");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 84, 620, 30);

        eksit.setBackground(new java.awt.Color(255, 0, 0));
        eksit.setFont(new java.awt.Font("BlackHole BB", 1, 14)); // NOI18N
        eksit.setText("X");
        eksit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eksitMouseClicked(evt);
            }
        });
        getContentPane().add(eksit);
        eksit.setBounds(560, 10, 50, 30);

        layot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kantinku/gambar/hexagonal-shape-technology-background_31543-348.jpg"))); // NOI18N
        layot.setPreferredSize(new java.awt.Dimension(620, 440));
        getContentPane().add(layot);
        layot.setBounds(0, 0, 620, 440);

        geser.setText("jLabel2");
        geser.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                geserMouseDragged(evt);
            }
        });
        geser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                geserMousePressed(evt);
            }
        });
        getContentPane().add(geser);
        geser.setBounds(0, 0, 620, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eksitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eksitMouseClicked
        this.dispose();
    }//GEN-LAST:event_eksitMouseClicked

    private void geserMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_geserMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x-dragxmouse,y-dragymouse);
        System.out.println(x+","+y);
    }//GEN-LAST:event_geserMouseDragged

    private void geserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_geserMousePressed
        dragxmouse = evt.getX();
        dragymouse = evt.getY();
    }//GEN-LAST:event_geserMousePressed

    public static String getNama(){
        return nama;
    }
    public static String getId(){
        return id;
    }
  
    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        if(sbg.getSelectedIndex()==1){
        try{
            String sql = "select * from pembeli where nama_pembeli='"+uname.getText()+"' and password_pembeli='"+pasword.getText()+"';";
            rs = stat.executeQuery(sql);
            if(rs.next()){
                if(uname.getText().equals(rs.getString("nama_pembeli"))&& pasword.getText().equals(rs.getString("password_pembeli"))){
                    this.id=rs.getString("id_pembeli");
                    this.nama=uname.getText();
                    JOptionPane.showMessageDialog(null, "Login Berhasil");
                    Menu m = new Menu();
                    m.setVisible(true);
                    this.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(null, "username atau password salah");
            }             
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        }else if(sbg.getSelectedIndex()==2){
            try{
            String sql = "select * from penjual where nama_penjual='"+uname.getText()+"' and password_penjual='"+pasword.getText()+"';";
            rs = stat.executeQuery(sql);
            if(rs.next()){
                if(uname.getText().equals(rs.getString("nama_penjual"))&& pasword.getText().equals(rs.getString("password_penjual"))){
                    this.id=rs.getString("id_penjual");
                    this.nama=uname.getText();
                    JOptionPane.showMessageDialog(null, "Login Berhasil");
                    Penjual p = new Penjual();
                    p.setVisible(true);
                    this.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(null, "username atau password salah");
            }             
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }            
        }else if(sbg.getSelectedIndex()==3){
            try{
            String sql = "select * from kasir where nama_kasir='"+uname.getText()+"' and password_kasir='"+pasword.getText()+"';";
            rs = stat.executeQuery(sql);
            if(rs.next()){
                if(uname.getText().equals(rs.getString("nama_kasir"))&& pasword.getText().equals(rs.getString("password_kasir"))){
                    this.id=rs.getString("id_kasir");
                    this.nama=uname.getText();
                    JOptionPane.showMessageDialog(null, "Login Berhasil");
                    Kasir k = new Kasir();
                    k.setVisible(true);
                    this.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(null, "username atau password salah");
            }             
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        }else{
            JOptionPane.showMessageDialog(null, "Not Found");
        }
    }//GEN-LAST:event_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eksit;
    private javax.swing.JLabel geser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel layot;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField pasword;
    private javax.swing.JComboBox<String> sbg;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables
}
