/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kantinku;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kris Cyber
 */
public class Menu extends javax.swing.JFrame  {

    int dragxmouse;
    int dragymouse;
    
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    
    public static String idm;
    
    public Menu() {
        initComponents();
        this.setBackground(new Color(0,0,0,0));
        Koneksi DB = new Koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
        tampilkan();
    }
    
    public static String getIdm(){
        return idm;
    }

    public void tampilkan(){
        DefaultTableModel tb = new DefaultTableModel();
        tb.addColumn("Kode");
        tb.addColumn("Menu");
        tb.addColumn("Harga");
        Dftmen.setModel(tb);
        
        try{
            String a = "select * from menunya;";
            rs = stat.executeQuery(a);
            while(rs.next()){
                Object[] obj = new Object[3];
                obj[0] = rs.getString("Id_Menu");
                obj[1] = rs.getString("Nama_Menu");
                obj[2] = rs.getString("Harga");
                tb.addRow(obj);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    public void tampilTabel(){
        DefaultTableModel tb = new DefaultTableModel();
        tb.addColumn("Nomor Meja");
        tb.addColumn("Nama Pembeli");
        tb.addColumn("Pesanan");
        tb.addColumn("Harga");
        Pesanan.setModel(tb);
        
        try{
            String a = "select * from (pesan left join pembeli on pesan.id_pembeli=pembeli.id_pembeli) left join menunya on pesan.id_menu=menunya.id_menu;";
            rs = stat.executeQuery(a);
                while(rs.next()){
                    Object[] obj = new Object[4];
                    obj[0] = rs.getString("Meja");
                    obj[1] = rs.getString("Nama_pembeli");
                    obj[2] = rs.getString("Nama_Menu");
                    obj[3] = rs.getString("Harga");
                    tb.addRow(obj);                   
                }
            String b = "select sum(harga) from menunya inner join pesan on menunya.id_menu=pesan.id_menu;";
            rs = stat.executeQuery(b);
            while(rs.next()){
                jum.setText(rs.getString("sum(harga)"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jum = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtKode = new javax.swing.JTextField();
        tambah = new javax.swing.JButton();
        Dmenu = new javax.swing.JScrollPane();
        Dftmen = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        Pesanan = new javax.swing.JTable();
        Pesan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        NoMeja = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        MenuMakanan = new javax.swing.JLabel();
        eksit = new javax.swing.JButton();
        layot = new javax.swing.JLabel();
        geser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(375, 165));
        setMinimumSize(new java.awt.Dimension(620, 440));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("BlackHole BB", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Total:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(324, 334, 100, 40);

        jum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jum);
        jum.setBounds(399, 340, 130, 30);
        getContentPane().add(txtHarga);
        txtHarga.setBounds(350, 210, 120, 30);
        getContentPane().add(txtNama);
        txtNama.setBounds(190, 210, 150, 30);
        getContentPane().add(txtKode);
        txtKode.setBounds(90, 210, 90, 30);

        tambah.setBackground(new java.awt.Color(51, 51, 51));
        tambah.setFont(new java.awt.Font("Antigrav BB", 1, 24)); // NOI18N
        tambah.setForeground(new java.awt.Color(255, 255, 255));
        tambah.setText("+");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah);
        tambah.setBounds(480, 210, 50, 30);

        Dftmen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Menu", "Harga"
            }
        ));
        Dftmen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DftmenMouseClicked(evt);
            }
        });
        Dmenu.setViewportView(Dftmen);

        getContentPane().add(Dmenu);
        Dmenu.setBounds(230, 110, 300, 90);

        Pesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nomor Meja", "Nama Pembeli", "Pesanan"
            }
        ));
        jScrollPane1.setViewportView(Pesanan);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(90, 250, 440, 80);

        Pesan.setFont(new java.awt.Font("BlackHole BB", 1, 24)); // NOI18N
        Pesan.setText("Pesan");
        Pesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesanActionPerformed(evt);
            }
        });
        getContentPane().add(Pesan);
        Pesan.setBounds(460, 390, 130, 33);

        jLabel2.setFont(new java.awt.Font("Antigrav BB", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Nomor Meja=");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 340, 130, 30);

        NoMeja.setFont(new java.awt.Font("Antigrav BB", 0, 24)); // NOI18N
        NoMeja.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NoMeja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoMejaActionPerformed(evt);
            }
        });
        getContentPane().add(NoMeja);
        NoMeja.setBounds(210, 340, 70, 30);

        jLabel1.setFont(new java.awt.Font("BlackHole BB", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Pilih menu:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 90, 200, 50);

        MenuMakanan.setFont(new java.awt.Font("BlackHole BB", 1, 36)); // NOI18N
        MenuMakanan.setForeground(new java.awt.Color(0, 255, 0));
        MenuMakanan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MenuMakanan.setText("Daftar Menu Makanan");
        getContentPane().add(MenuMakanan);
        MenuMakanan.setBounds(0, 20, 620, 40);

        eksit.setBackground(new java.awt.Color(255, 0, 0));
        eksit.setFont(new java.awt.Font("BlackHole BB", 1, 14)); // NOI18N
        eksit.setText("X");
        eksit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eksitMouseClicked(evt);
            }
        });
        getContentPane().add(eksit);
        eksit.setBounds(560, 10, 50, 30);

        layot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kantinku/gambar/hexagonal-shape-technology-background_31543-348.jpg"))); // NOI18N
        layot.setMaximumSize(new java.awt.Dimension(620, 440));
        layot.setMinimumSize(new java.awt.Dimension(620, 440));
        layot.setPreferredSize(new java.awt.Dimension(620, 440));
        getContentPane().add(layot);
        layot.setBounds(0, 0, 620, 440);

        geser.setText("jLabel2");
        geser.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                geserMouseDragged(evt);
            }
        });
        geser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                geserMousePressed(evt);
            }
        });
        getContentPane().add(geser);
        geser.setBounds(0, 0, 620, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eksitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eksitMouseClicked
        this.dispose();
    }//GEN-LAST:event_eksitMouseClicked

    private void geserMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_geserMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x-dragxmouse,y-dragymouse);
        System.out.println(x+","+y);
    }//GEN-LAST:event_geserMouseDragged

    private void geserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_geserMousePressed
        dragxmouse = evt.getX();
        dragymouse = evt.getY();
    }//GEN-LAST:event_geserMousePressed

    private void PesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesanActionPerformed
        JOptionPane.showMessageDialog(null, "Terimakasih, pesanan anda sedang diproses \n Silakan lakukan pembayaran di kasir.");
        Nota n = new Nota();
        n.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PesanActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        try{
            String idk = "'KA001',";
            String meja = "'"+NoMeja.getText()+"',";
            String id = "'"+Login.id+"',";
            String kode = "'"+txtKode.getText()+"',";
            String tang = "'"+Tanggal.getTgl()+"'";
                try{
                String ord = "INSERT INTO Pesan(`meja`,`id_pembeli`,`id_menu`,`id_kasir`,`tgl_beli`) VALUES ("+meja+id+kode+idk+tang+");";
                PreparedStatement pre = (PreparedStatement) con.prepareStatement(ord);
                pre.executeUpdate();
                pre.close();
                JOptionPane.showMessageDialog(null, "Berhasil menambah pesanan.");
                tampilTabel();
                } catch (Exception ex) {
                    System.out.println(ex);
                }    
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Failed");
        }
    }//GEN-LAST:event_tambahActionPerformed

    private void NoMejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoMejaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoMejaActionPerformed

    private void DftmenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DftmenMouseClicked
        int baris = Dftmen.rowAtPoint(evt.getPoint());
        String ID = Dftmen.getValueAt(baris, 0).toString();
        txtKode.setText(ID);
        String Nm = Dftmen.getValueAt(baris, 1).toString();
        txtNama.setText(Nm);
        String Harga = Dftmen.getValueAt(baris, 2).toString();
        txtHarga.setText(Harga);
    }//GEN-LAST:event_DftmenMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Dftmen;
    private javax.swing.JScrollPane Dmenu;
    private javax.swing.JLabel MenuMakanan;
    private javax.swing.JTextField NoMeja;
    private javax.swing.JButton Pesan;
    private javax.swing.JTable Pesanan;
    private javax.swing.JButton eksit;
    private javax.swing.JLabel geser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jum;
    private javax.swing.JLabel layot;
    private javax.swing.JButton tambah;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
