/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kantinku;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kris Cyber
 */
public class Penjual extends javax.swing.JFrame {

    int dragxmouse;
    int dragymouse;
    
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    
    public Penjual() {
        initComponents();
        this.setBackground(new Color(0,0,0,0));
        Koneksi DB = new Koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
        tampilTabel();
    }

    public void tampilTabel(){
        DefaultTableModel tb = new DefaultTableModel();
        tb.addColumn("Id menu");
        tb.addColumn("Nama menu");
        tb.addColumn("Harga");
        Dataku.setModel(tb);
        
        try{
            String a = "select * from menunya;";
            rs = stat.executeQuery(a);
            while(rs.next()){
                Object[] obj = new Object[3];
                obj[0] = rs.getString("Id_menu");
                obj[1] = rs.getString("Nama_menu");
                obj[2] = rs.getString("Harga");
                tb.addRow(obj);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        harmenu = new javax.swing.JTextField();
        namenu = new javax.swing.JTextField();
        idmenu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Apdet = new javax.swing.JButton();
        Delet = new javax.swing.JButton();
        Insert = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Dataku = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        eksit = new javax.swing.JButton();
        layot = new javax.swing.JLabel();
        geser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(375, 165));
        setMinimumSize(new java.awt.Dimension(620, 440));
        setUndecorated(true);
        getContentPane().setLayout(null);

        harmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harmenuActionPerformed(evt);
            }
        });
        getContentPane().add(harmenu);
        harmenu.setBounds(210, 320, 320, 20);
        getContentPane().add(namenu);
        namenu.setBounds(210, 290, 320, 20);
        getContentPane().add(idmenu);
        idmenu.setBounds(210, 260, 320, 20);

        jLabel4.setFont(new java.awt.Font("Antigrav BB", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 255));
        jLabel4.setText("Harga:");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 320, 150, 20);

        jLabel3.setFont(new java.awt.Font("Antigrav BB", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setText("Id:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 260, 120, 20);

        jLabel2.setFont(new java.awt.Font("Antigrav BB", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setText("Nama:");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 290, 120, 20);

        Apdet.setBackground(new java.awt.Color(255, 255, 0));
        Apdet.setFont(new java.awt.Font("BlackHole BB", 1, 18)); // NOI18N
        Apdet.setText("Ubah");
        Apdet.setPreferredSize(new java.awt.Dimension(120, 40));
        Apdet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApdetActionPerformed(evt);
            }
        });
        getContentPane().add(Apdet);
        Apdet.setBounds(250, 375, 120, 40);

        Delet.setBackground(new java.awt.Color(255, 0, 0));
        Delet.setFont(new java.awt.Font("BlackHole BB", 1, 18)); // NOI18N
        Delet.setText("Hapus");
        Delet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletActionPerformed(evt);
            }
        });
        getContentPane().add(Delet);
        Delet.setBounds(410, 375, 120, 40);

        Insert.setBackground(new java.awt.Color(51, 255, 0));
        Insert.setFont(new java.awt.Font("BlackHole BB", 1, 18)); // NOI18N
        Insert.setText("Tambah");
        Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertActionPerformed(evt);
            }
        });
        getContentPane().add(Insert);
        Insert.setBounds(93, 375, 120, 40);

        Dataku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Id", "Nama", "Harga"
            }
        ));
        Dataku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DatakuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Dataku);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(90, 110, 440, 120);

        jLabel1.setFont(new java.awt.Font("BlackHole BB", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Informasi Makanan");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 10, 620, 60);

        eksit.setBackground(new java.awt.Color(255, 0, 0));
        eksit.setFont(new java.awt.Font("BlackHole BB", 1, 14)); // NOI18N
        eksit.setText("X");
        eksit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eksitMouseClicked(evt);
            }
        });
        getContentPane().add(eksit);
        eksit.setBounds(560, 10, 50, 30);

        layot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kantinku/gambar/hexagonal-shape-technology-background_31543-348.jpg"))); // NOI18N
        layot.setPreferredSize(new java.awt.Dimension(620, 440));
        getContentPane().add(layot);
        layot.setBounds(0, 0, 620, 440);

        geser.setText("jLabel2");
        geser.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                geserMouseDragged(evt);
            }
        });
        geser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                geserMousePressed(evt);
            }
        });
        getContentPane().add(geser);
        geser.setBounds(0, 0, 620, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eksitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eksitMouseClicked
        this.dispose();
    }//GEN-LAST:event_eksitMouseClicked

    private void geserMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_geserMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x-dragxmouse,y-dragymouse);
        System.out.println(x+","+y);
    }//GEN-LAST:event_geserMouseDragged

    private void geserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_geserMousePressed
        dragxmouse = evt.getX();
        dragymouse = evt.getY();
    }//GEN-LAST:event_geserMousePressed

    private void harmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harmenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_harmenuActionPerformed

    private void InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertActionPerformed
        try{
            Statement stat = con.createStatement();
            String id = "'"+idmenu.getText()+"',";
            String nama = "'"+namenu.getText()+"',";
            String harga = "'"+harmenu.getText()+"'";
            String idpj = "'"+Login.id+"',";
            try{
                String b = "INSERT INTO Menunya(`Id_penjual`,`Id_menu`,`Nama_menu`,`Harga`) VALUES ("+idpj+id+nama+harga+")";
                PreparedStatement p = (PreparedStatement) con.prepareStatement(b);
                p.executeUpdate();
                p.close();
                JOptionPane.showMessageDialog(null, "Berhasil menambah data.");
                tampilTabel();
            } catch (Exception ex) {
                System.out.println(ex);
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_InsertActionPerformed

    private void DeletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletActionPerformed
        try{            
            Statement stat = con.createStatement();
            String id = "'"+idmenu.getText()+"'";
            String nama = "'"+namenu.getText()+"',";
            String harga = "'"+harmenu.getText()+"'";
            
            try{
                String d = "DELETE FROM `menunya` WHERE `Id_menu`="+id+";"; 
                PreparedStatement del = (PreparedStatement) con.prepareStatement(d);
                del.executeUpdate();
                del.close();
                JOptionPane.showMessageDialog(null, "Berhasil menghapus data.");
                tampilTabel();
            } catch (Exception ex) {
                System.out.println(ex);
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_DeletActionPerformed

    private void ApdetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApdetActionPerformed
        try{
            Statement stat = con.createStatement();
            String id = "'"+idmenu.getText()+"'";
            String nama = "'"+namenu.getText()+"',";
            String harga = "'"+harmenu.getText()+"'";
            
            try{
                String a = "UPDATE `menunya` SET `Nama_menu`="+nama+"`Harga`="+harga+" WHERE `Id_menu`="+id+"and"+harga+">0;";
                PreparedStatement ap = (PreparedStatement) con.prepareStatement(a);
                ap.executeUpdate();
                ap.close();
                JOptionPane.showMessageDialog(null, "Berhasil mengubah data.");
                tampilTabel();
            } catch (Exception ex) {
                System.out.println(ex);
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_ApdetActionPerformed

    private void DatakuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DatakuMouseClicked
        int baris = Dataku.rowAtPoint(evt.getPoint());
        String ID = Dataku.getValueAt(baris, 0).toString();
        idmenu.setText(ID);
        String Nm = Dataku.getValueAt(baris, 1).toString();
        namenu.setText(Nm);
        String Harga = Dataku.getValueAt(baris, 2).toString();
        harmenu.setText(Harga);
    }//GEN-LAST:event_DatakuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Penjual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Penjual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Penjual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Penjual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Penjual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Apdet;
    private javax.swing.JTable Dataku;
    private javax.swing.JButton Delet;
    private javax.swing.JButton Insert;
    private javax.swing.JButton eksit;
    private javax.swing.JLabel geser;
    private javax.swing.JTextField harmenu;
    private javax.swing.JTextField idmenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel layot;
    private javax.swing.JTextField namenu;
    // End of variables declaration//GEN-END:variables
}
